version: '3'
services:
  redpanda:
    image: docker.redpanda.com/vectorized/redpanda:v22.2.2
    container_name: price_watcher_broker
    command:
      - redpanda start
      - --kafka-addr PLAINTEXT://0.0.0.0:29092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092
    ports:
      - 29092:29092
